# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://remisharoon.github.io/
baseurl: /sustain/
title: Remis Haroon
author: Remis Haroon
description: Remis's personal blog and resume
avatar: profile.png
email: remisharoon@email.com
github: remisharoon # username
twitter: username
linkedin: remisharoon
stackoverflow: users/1843011/remis-haroon-رامز   #e.g: users/2735833/proton1h1
medium: remisharoon #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-0


# needed for travis-ci build
exclude: [vendor]
